# Generated by Django 5.2.8 on 2026-01-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_client_customer_rating_client_customer_stars_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='customer_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='client',
            name='executor_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
