# Generated by Django 5.2.8 on 2026-02-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_client_customer_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('uk', 'Українська'), ('sk', 'Slovenčina')], default='sk', max_length=5),
        ),
    ]
