# Generated by Django 5.2.8 on 2026-02-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_client_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='verification_photo',
            field=models.ImageField(blank=True, null=True, upload_to='verification_docs/%Y/%m/%d/', verbose_name='Фото для верификации'),
        ),
        migrations.AddField(
            model_name='client',
            name='verification_rejected_reason',
            field=models.CharField(blank=True, null=True),
        ),
    ]
