# Generated by Django 5.2.8 on 2026-02-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_client_verification_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Не верифицирован'), ('pending', 'Ожидает ответа'), ('verified', 'Верифицирован'), ('rejected', 'Отказано')], default='unverified', max_length=10),
        ),
    ]
