# Generated by Django 6.0.2 on 2026-03-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_final_days_message_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('admin', 'Сообщения администрации'), ('text', 'Обычное сообщение'), ('offer', 'Офер'), ('offer_accepted', 'Офер - принят'), ('offer_declined', 'Офер - отклонен'), ('dispute', 'Заказ - В споре'), ('order_completed', 'Заказ - завершен'), ('deleted', 'Удаленное')], default='text', max_length=20),
        ),
    ]
