# Generated by Django 5.2.8 on 2026-02-16 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisputeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('user', 'Пользователь'), ('admin', 'Админ')], default='user', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline_time', models.DateTimeField()),
                ('subject', models.CharField(choices=[('MATH', 'Математика'), ('ENG', 'Английский'), ('PHYS', 'Физика'), ('CHEM', 'Химия')], max_length=10)),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('pending', 'Ожидает'), ('in_progress', 'В работе'), ('dispute', 'Спор'), ('canceled', 'Отменен'), ('completed', 'Выполнен')], default='open', max_length=20)),
                ('final_price', models.PositiveIntegerField(blank=True, null=True)),
                ('final_days', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('expected_finish_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('on_review', 'На рассмотрении'), ('resolved', 'Решен'), ('closed', 'Закрыт')], default='open', max_length=20, verbose_name='Статус спора')),
                ('admin_decision', models.TextField(blank=True, null=True, verbose_name='Решение админа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('grade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_type', models.CharField(choices=[('customer', 'заказчик'), ('executor', 'исполнитель')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('offer', 'Предложение'), ('accepted', 'Принята'), ('rejected', 'Отклонена'), ('canceled', 'Отозвана'), ('completed', 'Завершена')], default='pending', max_length=20)),
                ('days_to_complete', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
