# Generated by Django 6.0.2 on 2026-02-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkorder',
            name='subject',
            field=models.CharField(choices=[('math', 'Математика'), ('inf', 'Информатика'), ('phys', 'Физика'), ('biology', 'Биология'), ('economy', 'Економика'), ('eng', 'Английский'), ('chem', 'Химия'), ('history', 'История'), ('art', 'Исскуство'), ('other', 'Другое')], max_length=10),
        ),
    ]
