# Generated by Django 4.2.17 on 2026-03-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_homeworkorder_order_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disputemessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='homeworkorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='homeworkorder',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('pending', 'Ожидает'), ('in_progress', 'В работе'), ('dispute', 'Спор'), ('canceled', 'Отменен'), ('completed', 'Выполнен')], db_index=True, default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='homeworkorder',
            name='subject',
            field=models.CharField(choices=[('math', 'Математика'), ('inf', 'Информатика'), ('phys', 'Физика'), ('biology', 'Биология'), ('economy', 'Економика'), ('eng', 'Английский'), ('chem', 'Химия'), ('history', 'История'), ('art', 'Исскуство'), ('other', 'Другое')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='orderdispute',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='orderdispute',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('on_review', 'На рассмотрении'), ('resolved', 'Решен'), ('closed', 'Закрыт')], db_index=True, default='open', max_length=20, verbose_name='Статус спора'),
        ),
        migrations.AlterField(
            model_name='orderreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='responsebid',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='responsebid',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('offer', 'Предложение'), ('accepted', 'Принята'), ('rejected', 'Отклонена'), ('canceled', 'Отозвана'), ('completed', 'Завершена')], db_index=True, default='pending', max_length=20),
        ),
    ]
