# Generated by Django 5.2.8 on 2025-11-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type_message',
            field=models.CharField(choices=[('text', 'Обычное сообщение'), ('offer', 'Офер')], default='text', max_length=20),
        ),
    ]
