# Generated by Django 5.2.8 on 2025-11-20 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_type_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='type_message',
            new_name='message_type',
        ),
    ]
