# Generated by Django 5.2.8 on 2025-11-21 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_type_message_message_message_type'),
        ('homework', '0005_homeworkorder_executor_homeworkorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='homework.homeworkorder'),
        ),
    ]
