# Generated by Django 5.2.8 on 2025-11-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Обычное сообщение'), ('offer', 'Офер'), ('offer_accepted', 'Офер - принят'), ('offer_declined', 'Офер - отклонен')], default='text', max_length=20),
        ),
    ]
