# Generated by Django 5.2.8 on 2026-01-07 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_conversation_last_message'),
        ('homework', '0009_homeworkorder_selected_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_messages', to='homework.homeworkorder'),
        ),
    ]
