# Generated by Django 5.2.8 on 2026-01-08 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_message_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message_type',
            new_name='type',
        ),
    ]
