# Generated by Django 5.2.8 on 2026-01-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('text', 'Обычное сообщение'), ('offer', 'Офер'), ('offer_accepted', 'Офер - принят'), ('offer_declined', 'Офер - отклонен'), ('order_completed', 'Заказ - завершен'), ('review_completed', 'Заказ - оценен')], default='text', max_length=20),
        ),
    ]
