# Generated by Django 5.2.8 on 2026-01-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('text', 'Обычное сообщение'), ('offer', 'Офер'), ('offer_accepted', 'Офер - принят'), ('offer_declined', 'Офер - отклонен'), ('dispute', 'Заказ - В споре'), ('order_completed', 'Заказ - завершен')], default='text', max_length=20),
        ),
    ]
