# Generated by Django 5.2.8 on 2025-11-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline_time', models.IntegerField()),
                ('subject', models.CharField(choices=[('MATH', 'Математика'), ('ENG', 'Английский'), ('PHYS', 'Физика'), ('CHEM', 'Химия')], max_length=10)),
            ],
        ),
    ]
