# Generated by Django 6.0.2 on 2026-02-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_alter_homeworkorder_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkorder',
            name='order_file',
            field=models.FileField(blank=True, null=True, upload_to='order_file/%Y/%m/%d/', verbose_name='Файл заказа'),
        ),
    ]
