# Generated by Django 5.2.8 on 2025-11-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_responsebid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkorder',
            name='deadline_time',
            field=models.DateTimeField(),
        ),
    ]
