# Generated by Django 4.2.17 on 2025-11-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0005_homeworkorder_executor_homeworkorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkorder',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('in_progress', 'В работе'), ('Completed', 'Выполнен')], default='open', max_length=20),
        ),
    ]
