# Generated by Django 5.2.8 on 2025-12-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0006_alter_homeworkorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsebid',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принят'), ('declined', 'Отклонен')], default='pending', max_length=20),
        ),
    ]
