# Generated by Django 5.2.8 on 2026-01-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0007_alter_responsebid_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkorder',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('pending', 'Ожидает'), ('in_progress', 'В работе'), ('Completed', 'Выполнен')], default='open', max_length=20),
        ),
    ]
