# Generated by Django 5.2.8 on 2026-01-07 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0008_alter_homeworkorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkorder',
            name='selected_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_in_order', to='homework.responsebid'),
        ),
    ]
