# Generated by Django 5.2.8 on 2026-01-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0009_homeworkorder_selected_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkorder',
            name='final_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homeworkorder',
            name='final_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
