# Generated by Django 5.2.8 on 2026-01-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0010_homeworkorder_final_days_homeworkorder_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkorder',
            name='final_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homeworkorder',
            name='final_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
