# Generated by Django 5.2.8 on 2026-01-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0011_alter_homeworkorder_final_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkorder',
            name='expected_finish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homeworkorder',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
