# Generated by Django 5.2.8 on 2026-01-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0012_homeworkorder_expected_finish_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkorder',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('pending', 'Ожидает'), ('in_progress', 'В работе'), ('сompleted', 'Выполнен')], default='open', max_length=20),
        ),
    ]
