# Generated by Django 5.2.8 on 2026-01-10 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0015_orderreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreview',
            name='grade',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
