# Generated by Django 5.2.8 on 2026-01-10 16:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0016_orderreview_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
