# Generated by Django 5.2.8 on 2026-01-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0018_alter_responsebid_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsebid',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принята'), ('rejected', 'Отклонена'), ('canceled', 'Отозвана'), ('completed', 'Завершена')], default='pending', max_length=20),
        ),
    ]
