# Generated by Django 5.2.8 on 2026-01-11 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0021_orderdisput'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdisput',
            old_name='created_by',
            new_name='author',
        ),
    ]
