# Generated by Django 5.2.8 on 2026-01-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0022_rename_created_by_orderdisput_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkorder',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('pending', 'Ожидает'), ('in_progress', 'В работе'), ('dispute', 'Спор'), ('canceled', 'Отменен'), ('completed', 'Выполнен')], default='open', max_length=20),
        ),
    ]
