# Generated by Django 5.2.8 on 2026-01-12 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0023_alter_homeworkorder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdisput',
            name='description',
        ),
    ]
