# Generated by Django 5.2.8 on 2026-01-12 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0024_remove_orderdisput_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdisput',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='homework.homeworkorder', verbose_name='Заказ'),
        ),
    ]
