# Generated by Django 5.2.8 on 2026-01-13 17:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0026_disputmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DisputMessage',
            new_name='DisputeMessage',
        ),
        migrations.RenameModel(
            old_name='OrderDisput',
            new_name='OrderDispute',
        ),
    ]
