# Generated by Django 5.2.8 on 2026-01-13 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0028_orderdispute_opponent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdispute',
            name='opponent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_disputes', to=settings.AUTH_USER_MODEL, verbose_name='Ответчик'),
            preserve_default=False,
        ),
    ]
