# Generated by Django 5.2.8 on 2026-01-17 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0029_alter_orderdispute_opponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreview',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='homework.homeworkorder'),
        ),
    ]
