# Generated by Django 5.2.8 on 2026-01-20 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0030_alter_orderreview_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdispute',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homework.disputemessage'),
        ),
    ]
