# Generated by Django 5.2.8 on 2026-01-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0031_orderdispute_last_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disputemessage',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='disputemessage',
            name='type',
            field=models.CharField(choices=[('user', 'Пользователь'), ('admin', 'Админ')], default='user', max_length=20),
        ),
    ]
