# Generated by Django 4.2.17 on 2026-03-08 15:23

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_feedback_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='verification_photo',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.get_verification_path, verbose_name='Фото для верификации'),
        ),
        migrations.AlterField(
            model_name='client',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Не верифицирован'), ('pending', 'Ожидает ответа'), ('verified', 'Верифицирован'), ('rejected', 'Отказано')], db_index=True, default='unverified', max_length=10),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
